name: Check Code Style

on:
  push:
    branches:
      - main

    pull_request:
      branches:
        - main

jobs:
  checkstyle_project:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone repo
        uses: actions/checkout@v2

      - name: Set python version
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.0"

      - name: Install dependencies
        run: |
          pip install flake8

      - name: Run linter
        run: |
          flake8 .
